### ISSUE TITLE
Usability: Change Search box default filter to everything

### ISSUE THREAD

**Issue by xpeterk** [saddlebackdev/church-management#1]
search box defaulting to last name. most users will start with first name. even better, default to everything

---
Web page: http://54.151.21.246:5002/index.html#/person-search
Browser: Firefox 38.0.5
OS: Windows NT 6.3; WOW64
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
User IP: 70.183.18.4

More details: https://my.bugdigger.com/b/5549635825303552

**Comment by ryan1234** [comment]
Closing and referencing: https://github.com/saddlebackdev/cm-core-fe/issues/136
