### ISSUE TITLE
BUG: Data cleared when clicing on Audit

### ISSUE THREAD

**Issue by xpeterk** [saddlebackdev/church-management#2]
Repo Steps:

1. Fill in Personal, Contact, and Decisions fields
2. Click on Audit Log
3. Click on back button on Audit screen
4. All fields are reset and blank

---
Web page: http://54.151.21.246:5002/index.html#/person-search/add
Browser: Firefox 38.0.5
OS: Windows NT 6.3; WOW64
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
User IP: 70.183.18.4

More details: https://my.bugdigger.com/b/6647360344031232

**Comment by xpeterk** [comment]
Same problem when after saving:

 1.   Fill in Personal, Contact, and Decisions fields
2.    Click on Save
 3.  Click on Audit Log
 4.   Click on back button on Audit screen
  5.  All fields are reset and blank

**Comment by ryan1234** [comment]
Closing and referencing: https://github.com/saddlebackdev/cm-core-fe/issues/134
