### ISSUE TITLE
BUG: Can't delete phone number

### ISSUE THREAD

**Issue by xpeterk** [saddlebackdev/church-management#3]
Reported using FREE BugDigger account (http://bugdigger.com)
---
Numbers entered into the phone field can not be removed:

1)backspace doesn't work
2) highlight cut doesn't work

---
Web page: http://54.151.21.246:5002/index.html#/person-search/add
Browser: Firefox 38.0.5
OS: Windows NT 6.3; WOW64
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
User IP: 70.183.18.4

More details: https://my.bugdigger.com/b/6523232836386816

**Comment by ryan1234** [comment]
Closing and referencing: https://github.com/saddlebackdev/cm-core-fe/issues/135
