### ISSUE TITLE
Data Disappears when adding first name

### ISSUE THREAD

**Issue by xpeterk** [saddlebackdev/church-management#4]
Reported using FREE BugDigger account (http://bugdigger.com)
---
Repo Steps:

1. Fill in all fields
2. Hit backspace on first name
3. All other fields will also clear out. Only the first name field should clear.

---
Web page: http://54.151.21.246:5002/index.html#/person-search/add
Browser: Firefox 38.0.5
OS: Windows NT 6.3; WOW64
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
User IP: 70.183.18.4

More details: https://my.bugdigger.com/b/6318633210871808

**Comment by xpeterk** [comment]
This appears to be an issue when atempting to change other fields as well

**Comment by xpeterk** [comment]
this may be related to the auto form filer add-in, but should be tested again to verify

**Comment by ryan1234** [comment]
Moving repos: https://github.com/saddlebackdev/cm-core-fe/issues/133
