### ISSUE TITLE
Save removes first and last name

### ISSUE THREAD

**Issue by xpeterk** [saddlebackdev/church-management#5]
Reported using FREE BugDigger account (http://bugdigger.com)
---
When hitting save after filling out the form fields, first and last name fields become blank

---
Web page: http://54.151.21.246:5002/index.html#/person-search/add
Browser: Firefox 38.0.5
OS: Windows NT 6.3; WOW64
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
User IP: 70.183.18.4

More details: https://my.bugdigger.com/b/5593572401217536

**Comment by ryan1234** [comment]
Closing. Referenced in cm-core repo: https://github.com/saddlebackdev/cm-core-fe/issues/132
